# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificaion_type', models.CharField(choices=[('FO', 'food'), ('CL', 'clothing'), ('HO', 'housing'), ('TR', 'transportation'), ('ED', 'education'), ('EN', 'entertainment'), ('OT', 'others')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeAndExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_type', models.CharField(choices=[('IN', 'income'), ('EX', 'expense')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('CR', 'credit_card'), ('CA', 'cash'), ('OT', 'other')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField()),
                ('remark', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('incomeandexpense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.IncomeAndExpense')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Payment')),
            ],
        ),
        migrations.CreateModel(
            name='SubClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Classification')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
        ),
        migrations.AddField(
            model_name='receipt',
            name='subclassification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.SubClassification'),
        ),
    ]
