# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20161129_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='classificaion_type',
            field=models.CharField(choices=[('food', 'food'), ('clothing', 'clothing'), ('housing', 'housing'), ('transportation', 'transportation'), ('education', 'education'), ('entertainment', 'entertainment'), ('others', 'others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='incomeandexpense',
            name='income_type',
            field=models.CharField(choices=[('income', 'income'), ('expense', 'expense')], max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('credit_card', 'credit_card'), ('cash', 'cash'), ('other', 'other')], max_length=20),
        ),
    ]
