# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20161205_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyclicalexpenditure',
            name='expenditure_type',
            field=models.CharField(choices=[('month', 'month'), ('week', 'week')], default='month', max_length=10),
        ),
        migrations.AddField(
            model_name='cyclicalexpenditure',
            name='reminder_type',
            field=models.CharField(choices=[('month', 'month'), ('week', 'week')], default='month', max_length=10),
        ),
        migrations.AlterField(
            model_name='cyclicalexpenditure',
            name='expenditure_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cyclicalexpenditure',
            name='reminder_date',
            field=models.IntegerField(),
        ),
    ]
