# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20161206_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='classification_type',
            field=models.CharField(choices=[('food', 'food'), ('clothing', 'clothing'), ('housing', 'housing'), ('transportation', 'transportation'), ('education', 'education'), ('entertainment', 'entertainment'), ('others', 'others'), ('revenue', 'revenue'), ('invest_revenue', 'invest_revenue'), ('other_revenue', 'other_revenue')], max_length=20),
        ),
    ]
